### ISSUE TITLE
ModuleNotFoundError: No module named 'pointnet2_cuda'

### ISSUE THREAD

**Issue by huangqianhong** [wutong16/Density_aware_Chamfer_Distance#4]
Hi, can you help me? I  come  across  the problem when I run train.py:
Traceback (most recent call last):
  File "F:/github/Density_aware_Chamfer_Distance-main/train.py", line 287, in <module>
    train()
  File "F:/github/Density_aware_Chamfer_Distance-main/train.py", line 59, in train
    model_module = importlib.import_module('.%s' % args.model_name, 'models')
  File "D:\IDE\Anaconda\envs\dcd\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\github\Density_aware_Chamfer_Distance-main\models\vrcnet.py", line 7, in <module>
    from utils.model_utils import *
  File "F:\github\Density_aware_Chamfer_Distance-main\utils\model_utils.py", line 13, in <module>
    import utils.Pointnet2_PyTorch.pointnet2.pointnet2_utils as pn2
  File "F:\github\Density_aware_Chamfer_Distance-main\utils\Pointnet2_PyTorch\pointnet2\pointnet2_utils.py", line 9, in <module>
    import pointnet2_cuda as pointnet2
ModuleNotFoundError: No module named 'pointnet2_cuda'

Process finished with exit code 1

**Comment by wutong16** [comment]
Hi! Thank you for your attention to our work! 

Have you run `bash set_up.sh` to install pointnet2 modules?

**Comment by huangqianhong** [comment]
&nbsp;Sorry, I am using win10 system and cannot run .sh file，so did I need to run this project&nbsp; on linux system such as ubuntu?






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tong ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wutong16/Density_aware_Chamfer_Distance] ModuleNotFoundError: No module named &#39;pointnet2_cuda&#39; (Issue #4)





 
Hi! Thank you for your attention to our work!
 
Have you run bash set_up.sh to install pointnet2 modules?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wutong16** [comment]
Yes. The dependent modules should be installed correctly before we can run the code. 

Please try it on Linux then. Feel free to report any further issues.

**Comment by huangqianhong** [comment]
ok,Thank you very much,I am trying it again on linux.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tong ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 下午4:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wutong16/Density_aware_Chamfer_Distance] ModuleNotFoundError: No module named &#39;pointnet2_cuda&#39; (Issue #4)





 
Yes. The dependent modules should be installed correctly before we can run the code.
 
Please try it on Linux then. Feel free to report any further issues.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
